# Generated by Django 4.2.14 on 2024-07-21 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0002_phrase_translate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_learning_word', models.CharField(choices=[('Learning_0_stage', 'Learning_0_stage'), ('Learning_1_stage', 'Learning_1_stage'), ('Learning_2_stage', 'Learning_2_stage'), ('Learning_3_stage', 'Learning_3_stage'), ('Learning_4_stage', 'Learning_4_stage'), ('Learning_5_stage', 'Learning_5_stage'), ('Learned', 'Learned')], default='Learning_0_stage', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time_learning', models.DateTimeField(null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_word', to='account.learner')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word')),
            ],
            options={
                'unique_together': {('word', 'learner')},
            },
        ),
    ]
