services:
  db:
    image: postgres
    restart: always
    volumes:
      - .data/db:/var/lib/postgresql/data
    env_file:
      - .env

  cache:
    image: redis
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    build: .
    command: ["uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
      - "443:443"