# Generated by Django 4.2.14 on 2024-07-18 20:47

from django.db import migrations, models
import django.db.models.deletion
import word.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=955, null=True, unique=True)),
                ('rank', models.CharField(blank=True, default='22000', max_length=100, null=True)),
            ],
            options={
                'ordering': ['name', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')], max_length=200, verbose_name='region')),
                ('transcription', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('sound', models.FileField(blank=True, null=True, upload_to=word.models.sound_path)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=255)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('adjectival', 'adjectival'), ('noun', 'noun'), ('verb', 'verb'), ('alliance', 'alliance'), ('adverb', 'adverb'), ('pronoun', 'pronoun'), ('other', 'other'), ('pretext', 'pretext'), ('interjection', 'interjection'), ('article', 'article'), ('irregular verb', 'irregular verb')], max_length=200)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=500, unique=True)),
                ('translate', models.CharField(max_length=500)),
                ('words', models.ManyToManyField(blank=True, related_name='examples', to='word.word')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('adjectival', 'adjectival'), ('noun', 'noun'), ('verb', 'verb'), ('alliance', 'alliance'), ('adverb', 'adverb'), ('pronoun', 'pronoun'), ('other', 'other'), ('pretext', 'pretext'), ('interjection', 'interjection'), ('article', 'article'), ('irregular verb', 'irregular verb')], max_length=200)),
                ('general_meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('deep_meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('translate', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='word.word')),
            ],
        ),
    ]
