# Generated by Django 4.2.14 on 2024-07-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='translate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
